### 1. Defining workflows ###
### 2. Core components ###
name: Java CICD With Maven #opt but will show as action name on repo

on: #req triggers
  push: #runs when a user pushes
    branches: ["main"]

  pull_request: #runs when a user does a pr
    branches: ["main"]

jobs: #req actions
  build:
    uses: ./.github/workflows/build.yml

  test:
    needs: build
    uses: ./.github/workflows/test.yml

  deploy:
    needs: test
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: target-files
      - name: Display structure of downloaded files
        run: ls -R
      - name: Deploy
        ### 9. ENVIRONMENT VARIABLES ###
        ### 10. SECRETS ###
        run: echo "Deploying with ${{ secrets.AWS_ACCESS_KEY_ID }} and ${{ secrets.AWS_SECRET_ACCESS_KEY }} at ${{ vars.CONNECTION_STRING }}"
