name: Test

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: target-files
      - name: Display structure of downloaded files
        run: ls -R
      - name: Test with maven
        run: mvn test